import { Settings } from "lucide-react";
import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiOutlineArrowPath,
  HiOutlineSun,
  HiOutlineMoon,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineClipboard,
  HiOutlineMagnifyingGlass,
  HiOutlineLink,
  HiArrowUpRight,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineComputerDesktop,
  HiOutlineQuestionMarkCircle,
  HiOutlineInformationCircle,
  HiOutlineExclamationTriangle,
  HiOutlineExclamationCircle,
  HiOutlineCheckBadge,
  HiOutlineCheckCircle,
  HiOutlineXMark,
  HiOutlineUser,
  HiOutlineEyeDropper,
  HiOutlineMinus,
  HiOutlinePlus,
  HiOutlineCalendar,
  HiOutlineDocumentDuplicate,
  HiOutlineArrowRightOnRectangle,
  HiOutlineBell,
  HiOutlineBuildingLibrary,
  HiOutlineBanknotes,
  HiOutlineBookmarkSquare,
  HiOutlineBellAlert,
} from "react-icons/hi2";

import {
  HiOutlineEmojiHappy,
  HiOutlineCog,
} from "react-icons/hi";

import { CgProfile } from "react-icons/cg";
import { profile } from "console";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  light: HiOutlineSun,
  dark: HiOutlineMoon,
  help: HiOutlineQuestionMarkCircle,
  info: HiOutlineInformationCircle,
  warning: HiOutlineExclamationTriangle,
  danger: HiOutlineExclamationCircle,
  checkbox: HiOutlineCheckBadge,
  check: HiOutlineCheckCircle,
  copy: HiOutlineDocumentDuplicate,
  eyeDropper: HiOutlineEyeDropper,
  clipboard: HiOutlineClipboard,
  person: HiOutlineUser,
  close: HiOutlineXMark,
  openLink: HiOutlineLink,
  arrowUpRight: HiArrowUpRight,
  minus: HiOutlineMinus,
  plus: HiOutlinePlus,
  calendar: HiOutlineCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  security: HiOutlineShieldCheck,
  settings: HiOutlineCog,
  sparkle: HiOutlineSparkles,
  computer: HiOutlineComputerDesktop,
  logout: HiOutlineArrowRightOnRectangle,
  notification: HiOutlineBell,
  home: HiOutlineBuildingLibrary,
  money: HiOutlineBanknotes,
  invoice: HiOutlineBookmarkSquare,
  notificationalert: HiOutlineBellAlert,
  emojihappy: HiOutlineEmojiHappy,
  profile: CgProfile,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
